#!/sbin/busybox sh

if [ "a$2" != "a" ]; then
	defaultrom=$2;

	case "${defaultrom}" in
		0)
			echo "0" > $EXTERNAL_STORAGE/.defaultrom;
		;;
		1)
			echo "1" > $EXTERNAL_STORAGE/.defaultrom;
		;;
	esac;
fi;

echo ${defaultrom};
